# Generated by Django 4.2.5 on 2023-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Necklace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="necklaces/")),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
