# Generated by Django 4.2.5 on 2023-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_comment3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="necklace",
            name="image",
        ),
        migrations.AddField(
            model_name="necklace",
            name="main_image",
            field=models.ImageField(blank=True, upload_to="necklaces/%Y/%m/%d/"),
        ),
    ]
