# Generated by Django 4.2.5 on 2023-10-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_remove_necklace_image_necklace_main_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="necklace",
            old_name="main_image",
            new_name="image",
        ),
    ]
