# Generated by Django 4.2.5 on 2023-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_rename_main_image_necklace_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="necklace",
            name="image",
            field=models.ImageField(blank=True, upload_to="necklaces/"),
        ),
    ]
